services:
  nginx-monitor:
    build:
      context: ..
      dockerfile: dockerized/Dockerfile
      args:
        BASE_IMAGE: "debian:bookworm-slim"
        NGINX_VERSION: "1.28.0"
        OPENSSL_RUNTIME_PACKAGE: "libssl3"
    image: ngx-http-monitoring-module:local
    container_name: ngx-http-monitoring-module
    ports:
      - "8080:8080"
    restart: unless-stopped
